# Generated by Django 4.1.1 on 2022-09-30 16:55

from django.db import migrations, models
import image_processing.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedimage',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to=image_processing.models.upload_to_combined),
        ),
    ]
